-- SOLO DESARROLLO LOCAL: usuario no-superuser para probar RLS de verdad.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='xolum_local_app') THEN
    CREATE ROLE xolum_local_app LOGIN PASSWORD 'xolum_app_local_2026' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END $$;

GRANT CONNECT ON DATABASE xolum_fiscal TO xolum_local_app;
GRANT USAGE ON SCHEMA public TO xolum_local_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO xolum_local_app;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO xolum_local_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO xolum_local_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE,SELECT ON SEQUENCES TO xolum_local_app;
